version: '3.2'
services:
  chart:
    image: manuelag19/youokay
    depends_on:
      - mongo
    ports:
      - '8080:4444'
    links:
      - "mongo:db"
      - "mongo:database"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'