service: daily-cron
# our Serverless Dashboard account name
tenant: manuelag19
# our Serverless Dashboard application name
app: youokay

provider:
  name: aws
  runtime: nodejs12
  region: 'us-east-1'
  frameworkVersion: ">=1.43.0"
  timeout: 900
  environment:
    SERVICE_URL: ${file(.env):SERVICE_URL}
functions:
  checkin:
    handler: handler.checkin
    events:
      # every 2 minutes
      - schedule: rate(2 minutes)