service: daily-cron
# our Serverless Dashboard account name
tenant: manuelag19
# our Serverless Dashboard application name
app: youokay

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900
  environment:
    SERVICE_URL: ${param:SERVICE_URL}
    ACCOUNTSID: ${param:ACCOUNTSID}
    AUTHTOKEN: ${param:AUTHTOKEN}
functions:
  checkin:
    handler: handler.checkin
    events:
      - schedule: cron(15/2 21 * * ? *)